services:
- type: web
  name: backend
  env: python
  plan: free
  repo: auto
  dir: Backend
  branch: main
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
  envVars:
    - key: OPENAI_API_KEY
      fromSecret: OPENAI_API_KEY

- type: static_site
  name: frontend
  plan: free
  repo: auto
  dir: Frontend/frontend
  branch: main
  buildCommand: npm ci && npm run build
  publishPath: build
  envVars:
    - key: REACT_APP_API_URL
      fromSecret: REACT_APP_API_URL
