services:
- type: web
  name: ai-code-reviewer-backend
  env: python
  plan: free
  repo: auto
  rootDir: Backend
  branch: main
  buildCommand: pip install -r requirements.txt && python build_vector_store.py
  startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
  envVars:
    - key: GROQ_API_KEY
      sync: false
    - key: PYTHON_VERSION
      value: "3.11.0"

- type: web
  name: ai-code-reviewer-frontend
  env: static
  plan: free
  repo: auto
  rootDir: Frontend/frontend
  branch: main
  buildCommand: npm ci && npm run build
  staticPublishPath: build
  envVars:
    - key: REACT_APP_API_URL
      sync: false
